### ISSUE TITLE
Auto Increment na IDkach

### ISSUE THREAD

**Issue by Ptrboro** [Helliox/HolidayManager#1]
To nie powinno być autoinkrementowane? Na kilku tabelach jest auto increment, na kilku nie

https://github.com/Helliox/HolidayManager/blob/b0dc617c6fd654d8bd3525c63a37c7c4da09201f/src/main/resources/database/TestDatabaseMYSQLdump.sql#L104

**Comment by Helliox** [comment]
Tak powinno, ten schemat bazy był nieaktualny, teraz już wszystko jest okej.

**Comment by Helliox** [comment]
Powinno, dopisałem to zaraz po pushu, lokalnie już naprawione :)
